vz = W + WBG;
vx = U + UBG;
wp = vz(2:end  ,2:end-1);
wm = vz(1:end-1,2:end-1);
up = vx(2:end-1,2:end  );
um = vx(2:end-1,1:end-1);

a   = 1/f0 - f;
acc = a(2:end-1,2:end-1);
ajp = a(3:end  ,2:end-1);  ajpp = a([4:end,3      ],2:end-1);
ajm = a(1:end-2,2:end-1);  ajmm = a([end-2,1:end-3],2:end-1);
aip = a(2:end-1,3:end  );  aipp = a(2:end-1,[4:end,3      ]);
aim = a(2:end-1,1:end-2);  aimm = a(2:end-1,[end-2,1:end-3]);

Div_fV(2:end-1,2:end-1)   =     up .*(-(aipp-aip)./h./8 + (aip + acc)./h./2 + (acc-aim )./h./8) ...
                          - abs(up).*(-(aipp-aip)./h./8 + (aip - acc)./h./4 - (acc-aim )./h./8) ...
                          -     um .*(-(aip -acc)./h./8 + (acc + aim)./h./2 + (aim-aimm)./h./8) ...
                          + abs(um).*(-(aip -acc)./h./8 + (acc - aim)./h./4 - (aim-aimm)./h./8) ...
                          +     wp .*(-(ajpp-ajp)./h./8 + (ajp + acc)./h./2 + (acc-ajm )./h./8) ...
                          - abs(wp).*(-(ajpp-ajp)./h./8 + (ajp - acc)./h./4 - (acc-ajm )./h./8) ...
                          -     wm .*(-(ajp -acc)./h./8 + (acc + ajm)./h./2 + (ajm-ajmm)./h./8) ...
                          + abs(wm).*(-(ajp -acc)./h./8 + (acc - ajm)./h./4 - (ajm-ajmm)./h./8);

% Div_fV(2:end-1,2:end-1) = ((acc+ajp)/2.*wp - (acc+ajm)/2.*wm)/h ...
%                         + ((acc+aip)/2.*up - (acc+aim)/2.*um)/h;
